@extends('layouts.admin')

@section('content')
<div class="container-fluid py-4">
    {{-- NexusCRM Breadcrumbs & Header --}}
    <nav aria-label="breadcrumb" class="mb-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}" class="text-decoration-none text-muted">{{ __('admins.dashboard') }}</a></li>
            <li class="breadcrumb-item active fw-bold text-primary" aria-current="page">{{ __('clients.index_title') }}</li>
        </ol>
    </nav>

    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h3 class="fw-bold mb-0 text-dark">{{ __('clients.index_title') }}</h3>
            <p class="text-muted small mb-0">{{ __('Manage and monitor your customer relationships.') }}</p>
        </div>

        @if (!isSales())
            <a href="{{ route('admin.clients.create') }}" class="btn btn-primary shadow-sm px-4">
                <i class="ti ti-plus me-1 fs-5"></i>
                {{ __('clients.create_title') }}
            </a>
        @endif
    </div>

    <x-flash-success />
    <x-flash-error />

    {{-- Datatable Container Card --}}
    <div class="card shadow-sm border-0">
        <div class="card-header bg-white py-3 border-bottom d-flex align-items-center justify-content-between">
            <h5 class="mb-0 fw-bold text-primary">
                <i class="ti ti-users me-2"></i>{{ __('clients.client_list') }}
            </h5>
            {{-- Optional: Add a quick filter button or export button here --}}
            <div class="card-actions">
                <button class="btn btn-sm btn-light border" onclick="window.location.reload();">
                    <i class="ti ti-refresh"></i>
                </button>
            </div>
        </div>
        
        <div class="card-body p-0">
            <div class="table-responsive">
                {{-- NexusCRM Custom Datatable Wrapper --}}
                <div class="p-3">
                    <x-datatable
                        :ajaxUrl="route('admin.clients.data')"
                        :columns="$columns"
                        :renderComponents="$renderComponents"
                        :customActionsView="$customActionsView"
                    />
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    /* NexusCRM Custom Styling for Datatables */
    .card {
        border-radius: 12px;
    }
    .breadcrumb-item + .breadcrumb-item::before {
        content: "›";
        font-size: 1.2rem;
        vertical-align: middle;
        line-height: 1;
    }
    /* Style the search input and length menu if generated by x-datatable */
    .dataTables_wrapper .dataTables_filter input {
        border: 1px solid #e9ecef;
        border-radius: 8px;
        padding: 6px 12px;
    }
    [data-bs-theme="dark"] .dataTables_wrapper .dataTables_filter input {
        background-color: #0f172a !important;
        border-color: #334155 !important;
        color: #e2e8f0 !important;
    }
    .dataTables_wrapper .dataTables_length select {
        border: 1px solid #e9ecef;
        border-radius: 8px;
    }
    [data-bs-theme="dark"] .dataTables_wrapper .dataTables_length select {
        background-color: #0f172a !important;
        border-color: #334155 !important;
        color: #e2e8f0 !important;
    }
    .table thead th {
        background-color: #f8f9fa;
        text-transform: uppercase;
        font-size: 0.75rem;
        letter-spacing: 0.5px;
        font-weight: 700;
        color: #6c757d;
        border-bottom-width: 1px;
    }
    [data-bs-theme="dark"] .table thead th {
        background-color: #334155 !important;
        color: #e2e8f0 !important;
        border-bottom-color: #475569 !important;
    }
</style>
@endsection